import React, { useState } from 'react';
import { generateStudyPlan } from '../services/geminiService';
import { cfApi } from '../services/cfApi';
import { CFUser } from '../types';

interface StudyPlanProps {
  handle: string;
}

export const StudyPlan: React.FC<StudyPlanProps> = ({ handle }) => {
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    setPlan(null);
    try {
      const [user] = await cfApi.getUserInfo(handle);
      const submissions = await cfApi.getUserStatus(handle, 50);
      
      if (!user) throw new Error("User info not found");

      const generatedPlan = await generateStudyPlan(user, submissions);
      setPlan(generatedPlan);
    } catch (error) {
      console.error("Error generating plan:", error);
      setPlan("An error occurred while communicating with the AI. Please check your network and API key.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h2 className="text-2xl font-bold text-gray-800 mb-2">AI Performance Coach</h2>
        <p className="text-gray-600 mb-6">
          Use Gemini AI to analyze your recent Codeforces performance and generate a personalized study plan to improve your rating.
        </p>

        <div className="flex justify-center">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className={`px-6 py-3 rounded-md text-white font-medium text-lg transition-all ${
              loading 
                ? 'bg-blue-400 cursor-not-allowed' 
                : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 shadow-lg hover:shadow-xl'
            }`}
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Analyzing Profile...
              </span>
            ) : (
              'Generate My Study Plan'
            )}
          </button>
        </div>
      </div>

      {plan && (
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 animate-fade-in">
          <h3 className="text-xl font-bold text-gray-800 mb-4 border-b pb-2">Your Personal Plan</h3>
          <div className="prose prose-blue max-w-none text-gray-700 whitespace-pre-wrap leading-relaxed">
            {plan}
          </div>
          <div className="mt-6 p-4 bg-yellow-50 text-yellow-800 text-sm rounded border border-yellow-200">
            <strong>Note:</strong> This plan is generated by AI based on your public data. Always cross-reference with official editorials.
          </div>
        </div>
      )}
    </div>
  );
};